### PR TITLE
influxdb: Enable devnet2 on 8092/UDP

### PR DESCRIPTION
**Pull request by woky**

### CODE REVIEW

**Review by adaszko — APPROVED** [review]

**Review by adaszko — CHANGES_REQUESTED** [review]
I approved too early.

**Comment by adaszko** [comment]
You're going to need a bunch of other stuff.  Take a look at https://github.com/rchain/perf-harness/pull/87/files

**Comment by woky** [comment]
@adaszko Updated.

**Review by adaszko — APPROVED** [review]
👍 Ping me if you want me to deploy it once it's merged.  It requires the [Ansible incantation](https://github.com/rchain/perf-harness#deployment).

**Comment by woky** [comment]
@adaszko Feel free to deploy.

**Pull request merged**
